T1=table(svMagnDipolb,svrsunecef,svrsuneci,svWb,svNormWb,svWorbb,...
        svNob,svQjb,svHrwb,svHrwp,svRWRate,svTrwb,svTgravb,...
        svTab,svTgyrob,svTmb,svMagnMomentp);
        
T2=table(svQjbmes,svNobmes,svWmesb,svTrwreqb,svTb,svHrwreqb,...
        svHrwreqp,svRWRateReq,svBmesb,svBdot,svMagnMomentReqp,...
        svUunload,svUdempf);
writetable(T1,'stab3testcase2.xlsx','Sheet',1);
writetable(T2,'stab3testcase2.xlsx','Sheet',2);    