function [rsunj, rsunecef, rtasc, decl, LightFlag] = calc_sun(logorb, sgp4params, earthparams)
%calc_sun Рассчитывает вектор направления на Солнце, а также участки
%   света/тени
%
    AU2KM = 149597870.0; % au to km
    
    rsunj     = zeros(size(logorb.rj2000,1),3);
    rsunecef  = zeros(size(logorb.rj2000,1),3);
    rtasc     = zeros(size(logorb.rj2000,1),1);
    decl      = zeros(size(logorb.rj2000,1),1);
    LightFlag = zeros(size(logorb.rj2000,1),1);
    
    for i=1:size(logorb.rj2000,1)
    % Найдем положение Солнца
        [rsunj(i,1:3), rtasc(i), decl(i)] = sun(logorb.jdut1(i));
    % Перепроектируем положение Солнца на ECEF
        [rsunecef(i,1:3),~,~] = eci2ecef(...
            rsunj(i,1:3)',...
            [0;0;0],...
            [0;0;0],...
            logorb.ttt(i),...
            logorb.jdut1(i),...
            earthparams.lod,...
            earthparams.xp,...
            earthparams.yp,...
            sgp4params.eqeterms,...
            earthparams.ddpsi,...
            earthparams.ddeps );
    % В тени или на свету аппарат? (цилиндрическая тень)
        LightFlag(i) = sight( rsunj(i,1:3)*AU2KM,logorb.rj2000(i,:),'e');
    end

