function [MagnField_j, MagnFieldECEF] = calc_magn(logorb, sgp4params, earthparams)
%calc_magn Расчитываем магнитное поле в заданной точки пространства с
%   recefпомощью выбранной модели
%Входы:
%   recef  - Матрица [Nx3]. N радиус-векторов в ECEF в км
%   model  - 'IGRF'(по умолчанию) или 'dipol'
%   params - Параметры моделирования
%Выходы:
%   MagnField_j   - Матрица [Nx3] магнитного поля в заданной точке в J2000
%   MagnFieldECEF - Матрица [Nx3] магнитного поля в заданной точке в ECEF

MagnFieldECEF = zeros(size(logorb.recef,1),3);
MagnField_j   = zeros(size(logorb.recef,1),3);
if strcmp(earthparams.MagnModel,'dipol')
    for i=1:size(logorb.recef,1)
        normR = norm(logorb.recef(i,:)); % км
        % B = M*(3*(R,R)-|R|^2)/|R|^5
        
        MagnFieldECEF(i,1:3) = MagnMomentum*(3*(logorb.recef(i,:))*logorb.recef(i,:)'-normR^2)/normR^5;% нТл
        [MagnField_j(i,1:3),~,~] = ecef2eci(...
            MagnFieldECEF(i,1:3)',...
            [0 0 0]',...
            [0 0 0]',...
            logorb.ttt(i),...
            logorb.jdut1(i),...
            earthparams.lod,...
            earthparams.xp,...
            earthparams.yp,...
            sgp4params.eqeterms,...
            earthparams.ddpsi,...
            earthparams.ddeps...
        );
    end
    
else
    %Модель IGRF 12
	%Найдем магнитное поле в NED
    for i=1:size(logorb.recef,1)
        [MagnFieldNED, ~, ~, ~, ~] = igrfmagm(...
            logorb.hellp(i)*1000,...
            rad2deg(logorb.latgd(i)),...
            rad2deg(logorb.lon(i)),...
            logorb.deciyear(i),...
            12....
        );
        %Пересчитаем в ECEF
        [Vect(1), Vect(2), Vect(3)] = ned2ecef( ...
            MagnFieldNED(:,1)',...
            MagnFieldNED(:,2)',...
            MagnFieldNED(:,3)',...
            logorb.latgd(i),...
            logorb.lon(i),...
            logorb.hellp(i)*1000,...
            wgs84Ellipsoid,...
            'radians'...
        );
        %Выше мы посчитали координаты конца вектора магнитной индукции в ECEF,
        %нужно еще вычесть координаты начала координат NED в ECEF

        [x0ecef,y0ecef,z0ecef] = ned2ecef( ...
            0,0,0,...
            logorb.latgd(i),...
            logorb.lon(i),...
            logorb.hellp(i)*1000,...
            wgs84Ellipsoid,...
            'radians'...
        );
        MagnFieldECEF(i,1:3) = Vect-[x0ecef y0ecef z0ecef];
        [MagnField_j(i,1:3),~,~] = ecef2eci(...
            MagnFieldECEF(i,1:3)',...
            [0 0 0]',...
            [0 0 0]',...
            logorb.ttt(i),...
            logorb.jdut1(i),...
            earthparams.lod,...
            earthparams.xp,...
            earthparams.yp,...
            sgp4params.eqeterms,...
            earthparams.ddpsi,...
            earthparams.ddeps...
        );
    end
end


